"""
Django settings for reyes_estancias project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import environ
from celery.schedules import crontab

#SITE_BASE_URL:
SITE_BASE_URL = os.environ.get("SITE_BASE_URL", "http://127.0.0.1:8000")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Inicializar environ
env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=False)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=[])


# Security settings for production
if not DEBUG:
    # Railway (y cualquier reverse proxy) termina SSL en el proxy y reenvía
    # X-Forwarded-Proto. SECURE_SSL_REDIRECT=True causaría bucles de redirección.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000  # 1 año
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# Application definition

JAZZMIN_SETTINGS = {
    "site_title": "Reyes Estancias",
    "site_header": "Reyes Estancias",
    "site_brand": "Reyes Estancias",
    "welcome_sign": "Bienvenido al panel de administración",
    "copyright": "Reyes Estancias",
    "search_model": ["bookings.Booking", "accounts.CustomUser"],
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "order_with_respect_to": [
        "bookings",
        "properties",
        "payments",
        "accounts",
        "registration",
    ],
    "icons": {
        "bookings.Booking": "fas fa-calendar-check",
        "bookings.BookingChangeLog": "fas fa-history",
        "properties.Property": "fas fa-home",
        "properties.PropertyImage": "fas fa-images",
        "payments.Payment": "fas fa-credit-card",
        "payments.RefundLog": "fas fa-undo",
        "accounts.CustomUser": "fas fa-users",
        "auth.Group": "fas fa-shield-alt",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": True,
    "show_ui_builder": False,
    "custom_css": "admin/css/custom_admin.css",
    "changeform_format": "horizontal_tabs",
    "language_chooser": False,
}

JAZZMIN_UI_TWEAKS = {
    "navbar": "navbar-white navbar-light",
    "navbar_fixed": True,
    "sidebar": "sidebar-light-primary",
    "sidebar_fixed": True,
    "accent": "accent-primary",
    "theme": "flatly",
    "default_theme_mode": "light",
}

INSTALLED_APPS = [
    'jazzmin',
    'cloudinary_storage',
    'registration',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary',
    'accounts',
    'properties',
    'bookings',
    'payments',
    'tailwind',
    'theme',
    'core',
]


TAILWIND_APP_NAME = 'theme'
NPM_BIN_PATH = env('NPM_BIN_PATH', default='npm')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
if DEBUG:
    INSTALLED_APPS += ['django_browser_reload']
    MIDDLEWARE += [
        "django_browser_reload.middleware.BrowserReloadMiddleware",
    ]


ROOT_URLCONF = 'reyes_estancias.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'reyes_estancias.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': env('DB_NAME'),      # nombre de tu base
        'USER': env('DB_USER'),            # tu usuario MySQL
        'PASSWORD': env('DB_PASSWORD'), # tu password
        'HOST': env('DB_HOST'),
        'PORT': env('DB_PORT'),
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Mexico_City'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

#Media files
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Cloudinary
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': env('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': env('CLOUDINARY_API_KEY'),
    'API_SECRET': env('CLOUDINARY_API_SECRET'),
}
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#Auth
LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "home"
LOGIN_URL = "login"

#Email config
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = env('EMAIL_HOST')
EMAIL_HOST_USER = env('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')
EMAIL_PORT = env.int('EMAIL_PORT', default=587)
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=True)
DEFAULT_FROM_EMAIL = 'no-reply@reyesestancias.com'


#Stripe
STRIPE_SECRET_KEY = env("STRIPE_SECRET_KEY")
STRIPE_PUBLISHABLE_KEY = env("STRIPE_PUBLISHABLE_KEY")
STRIPE_WEBHOOK_SECRET = env("STRIPE_WEBHOOK_SECRET")  # lo pondrás tras crear el webhook

# iCal Fetch Security Settings
ICAL_REQUEST_TIMEOUT = env.int('ICAL_REQUEST_TIMEOUT', default=10)  # segundos
ICAL_MAX_SIZE = env.int('ICAL_MAX_SIZE', default=5 * 1024 * 1024)  # 5 MB en bytes
ICAL_CACHE_TIMEOUT = env.int('ICAL_CACHE_TIMEOUT', default=900)  # 15 minutos en segundos
ICAL_ALLOWED_HOSTS = env.list('ICAL_ALLOWED_HOSTS', default=[
    'airbnb.com',
    'airbnb.es',
    'airbnb.mx',
    'calendar.google.com',
    'booking.com',
    'vrbo.com',
    'homeaway.com',
])

# Django Cache (usando Redis)
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': env('CELERY_BROKER_URL', default='redis://127.0.0.1:6379/0'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'CONNECTION_POOL_CLASS_KWARGS': {
                'max_connections': 50,
                'retry_on_timeout': True,
            },
            'SOCKET_CONNECT_TIMEOUT': 5,
            'SOCKET_TIMEOUT': 5,
        },
        'KEY_PREFIX': 'reyes_estancias',
        'TIMEOUT': 300,  # 5 minutos por defecto
    }
}

# Celery (Redis como broker y backend)
CELERY_BROKER_URL = env('CELERY_BROKER_URL', default='redis://127.0.0.1:6379/0')
CELERY_RESULT_BACKEND = env('CELERY_RESULT_BACKEND', default='redis://127.0.0.1:6379/1')
CELERY_TASK_ALWAYS_EAGER = False
CELERY_TIMEZONE = "America/Mexico_City"
CELERY_ENABLE_UTC = True
CELERY_BEAT_SCHEDULE = {
    "charge-balances-every-15-min": {
        "task": "payments.tasks.scan_and_charge_balances",
        "schedule": crontab(minute="*/15"),
        "args": (SITE_BASE_URL,),  # usa tu base
    },
    "mark-expired-bookings-daily": {
        "task": "bookings.tasks.mark_expired_bookings",
        "schedule": crontab(hour=3, minute=0),  # 3:00 AM cada día
    },
    "mark-completed-bookings-daily": {
        "task": "bookings.tasks.mark_completed_bookings",
        "schedule": crontab(hour=3, minute=15),  # 3:15 AM, tras mark-expired
    },
    "mark-expired-holds-hourly": {
        "task": "bookings.tasks.mark_expired_holds",
        "schedule": crontab(minute=0),  # Cada hora en punto
    },
    "sync-property-calendars-every-30-min": {
        "task": "properties.tasks.sync_all_property_calendars",
        "schedule": crontab(minute="*/30"),  # Cada 30 minutos
    },
}
CELERY_TASK_SERIALIZER = "json"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_RESULT_SERIALIZER = "json"

# Configuración de rendimiento y confiabilidad
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True  # Reintentar conexión al inicio
CELERY_TASK_TIME_LIMIT = 600  # 10 minutos - Límite duro para tareas
CELERY_TASK_SOFT_TIME_LIMIT = 540  # 9 minutos - Aviso antes del límite duro
CELERYD_MAX_TASKS_PER_CHILD = 1000  # Reiniciar worker cada 1000 tareas (evita memory leaks)
CELERY_TASK_ACKS_LATE = True  # Confirmar tareas después de completar (más seguro)
CELERY_WORKER_PREFETCH_MULTIPLIER = 1  # Prefetch de 1 tarea por worker (mejor distribución)

# Opciones de transporte (Redis)
CELERY_BROKER_TRANSPORT_OPTIONS = {
    'visibility_timeout': 3600,  # 1 hora - Tiempo antes de que una tarea se reintente
    'fanout_prefix': True,
    'fanout_patterns': True,
}

# Configuración de resultados
CELERY_RESULT_EXPIRES = 86400  # Los resultados expiran en 24 horas
CELERY_RESULT_BACKEND_TRANSPORT_OPTIONS = {
    'master_name': 'mymaster',  # Para Redis Sentinel (opcional)
}

# CELERY TESTS
CELERY_TASK_EAGER_PROPAGATES = True    # si falla, revienta el test

#ACCOUNTS APP
AUTH_USER_MODEL = "accounts.User"

# Logging configuration
# Directorio de logs (configurable via variable de entorno)
LOG_DIR = env('LOG_DIR', default=os.path.join(BASE_DIR, 'logs'))
LOG_LEVEL = env('LOG_LEVEL', default='DEBUG' if DEBUG else 'INFO')

# Crear directorio de logs si no existe
os.makedirs(LOG_DIR, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    # =========================================================================
    # FORMATTERS - Formatos de salida de logs
    # =========================================================================
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {name} {module}.{funcName}:{lineno} - {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'simple': {
            'format': '[{levelname}] {asctime} - {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'celery': {
            'format': '[{levelname}] {asctime} [Celery] {name} - {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },

    # =========================================================================
    # FILTERS - Filtros condicionales
    # =========================================================================
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },

    # =========================================================================
    # HANDLERS - Destinos de logs
    # =========================================================================
    'handlers': {
        # Console - Output a terminal (desarrollo)
        'console': {
            'level': LOG_LEVEL,
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },

        # Django general - Logs generales de Django
        'file_django': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'django.log'),
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },

        # Errors - Solo errores críticos (ERROR y CRITICAL)
        'file_errors': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'errors.log'),
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },

        # Security - Logs de seguridad
        'file_security': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'security.log'),
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },

        # iCal - Logs de sincronización de calendarios
        'file_ical': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'ical.log'),
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },

        # Payments - Logs de pagos y Stripe
        'file_payments': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'payments.log'),
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },

        # Celery - Logs de tareas Celery
        'file_celery': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'celery.log'),
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 5,
            'formatter': 'celery',
        },

        # Mail admins - Envía errores críticos por email (solo en producción)
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
            'filters': ['require_debug_false'],
            'formatter': 'verbose',
        },
    },

    # =========================================================================
    # LOGGERS - Configuración de loggers específicos
    # =========================================================================
    'loggers': {
        # Django core
        'django': {
            'handlers': ['console', 'file_django'],
            'level': 'INFO',
            'propagate': False,
        },

        # Django request (accesos HTTP)
        'django.request': {
            'handlers': ['console', 'file_django', 'file_errors'],
            'level': 'WARNING',
            'propagate': False,
        },

        # Django security
        'django.security': {
            'handlers': ['console', 'file_security', 'mail_admins'],
            'level': 'WARNING',
            'propagate': False,
        },

        # Django database queries (útil para debugging, desactivar en prod)
        'django.db.backends': {
            'handlers': ['console'] if DEBUG else [],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },

        # Properties app - General
        'properties': {
            'handlers': ['console', 'file_django'],
            'level': LOG_LEVEL,
            'propagate': False,
        },

        # Properties - iCal utils (sincronización de calendarios)
        'properties.utils.ical': {
            'handlers': ['console', 'file_ical', 'file_errors'],
            'level': 'INFO',
            'propagate': False,
        },

        # Properties - Tasks (tareas Celery de properties)
        'properties.tasks': {
            'handlers': ['console', 'file_ical', 'file_celery', 'file_errors'],
            'level': 'INFO',
            'propagate': False,
        },

        # Bookings app
        'bookings': {
            'handlers': ['console', 'file_django'],
            'level': LOG_LEVEL,
            'propagate': False,
        },

        # Bookings - Tasks (tareas Celery de bookings)
        'bookings.tasks': {
            'handlers': ['console', 'file_celery', 'file_errors'],
            'level': 'INFO',
            'propagate': False,
        },

        # Payments app
        'payments': {
            'handlers': ['console', 'file_payments', 'file_errors'],
            'level': LOG_LEVEL,
            'propagate': False,
        },

        # Payments - Tasks (tareas Celery de payments)
        'payments.tasks': {
            'handlers': ['console', 'file_payments', 'file_celery', 'file_errors'],
            'level': 'INFO',
            'propagate': False,
        },

        # Celery - General
        'celery': {
            'handlers': ['console', 'file_celery', 'file_errors'],
            'level': 'INFO',
            'propagate': False,
        },

        # Celery - Task execution
        'celery.task': {
            'handlers': ['console', 'file_celery'],
            'level': 'INFO',
            'propagate': False,
        },

        # Celery - Beat scheduler
        'celery.beat': {
            'handlers': ['console', 'file_celery'],
            'level': 'INFO',
            'propagate': False,
        },
    },

    # =========================================================================
    # ROOT LOGGER - Captura todos los logs no especificados arriba
    # =========================================================================
    'root': {
        'handlers': ['console', 'file_django', 'file_errors'],
        'level': LOG_LEVEL,
    },
}

# Configuración de ADMINS para recibir emails de errores (solo en producción)
if not DEBUG:
    ADMINS = [
        ('Admin Reyes Estancias', env('ADMIN_EMAIL', default='admin@reyes-estancias.com')),
    ]
    MANAGERS = ADMINS
