# Generated by Django 5.2 on 2026-07-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_ical_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='interaccion_viajeros',
            field=models.TextField(blank=True, null=True, verbose_name='Interacción con los viajeros'),
        ),
        migrations.AddField(
            model_name='property',
            name='otros_detalles',
            field=models.TextField(blank=True, null=True, verbose_name='Otros detalles importantes'),
        ),
        migrations.AddField(
            model_name='property',
            name='servicios_zonas_comunes',
            field=models.TextField(blank=True, null=True, verbose_name='Servicios y zonas comunes'),
        ),
        migrations.AddField(
            model_name='property',
            name='tu_propiedad',
            field=models.TextField(blank=True, null=True, verbose_name='Tu propiedad'),
        ),
    ]
