# Generated by Django 5.2 on 2026-07-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_description_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='email_group',
            field=models.CharField(choices=[('expo_aguamarina', 'Expo / Aguamarina'), ('departamentos', 'Departamentos'), ('otros', 'Resto de casas (Santa Anita, Moras...)')], default='otros', help_text='Determina qué instrucciones de llegada se envían al huésped.', max_length=30, verbose_name='Grupo de email de confirmación'),
        ),
    ]
