# Generated by Django 5.2 on 2026-07-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0017_booking_source_ical_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magiclink',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
