# Generated by Django 5.2 on 2026-07-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0018_alter_magiclink_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='airbnb_confirmation_code',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Código confirmación Airbnb'),
        ),
    ]
